[package]
name = "voting_contract"
authors = [""]
compiler_version = ">=0.1.0"
type = "lib"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v0.24.0", directory = "yarn-project/aztec-nr/aztec" }
