[package]
name = "donation_contract"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.1.9", directory = "noir-projects/aztec-nr/aztec" }
