printf '%s\n' \
'[package]' \
'name = "donation_contract"' \
'type = "contract"' \
'authors = [ "" ]' \
'compiler_version = ">=0.18.0"' \
'' \
'[dependencies]' \
'aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.1.9", directory = "noir-projects/aztec-nr/aztec" }' \
> Nargo.toml
